// 微信原生 Component 的动态 this 类型由开发者工具注入；领域模块保持严格类型。
// @ts-nocheck
import type { Hold, Layout } from '../../../src/domain/types.js'
import { circleHitTest, nearestHold, polygonHitTest } from '../../../src/domain/geometry.js'
import { clampTransform, imageToScreen, screenToImage } from '../../../src/domain/transform.js'
import { GestureController } from '../../../src/domain/gesture.js'
import { downloadCloudImage } from '../../services/layouts.js'

Component({ properties: { layout: { type: Object, value: null, observer() { this.initCanvas() } }, activeHolds: { type: Object, value: {}, observer() { this.render() } } }, data: { transform: { scale: 1, offsetX: 0, offsetY: 0 }, viewportWidth: 0, viewportHeight: 0, imageError: false }, methods: {
  initCanvas() { const query = wx.createSelectorQuery().in(this); query.select('#wallCanvas').fields({ node: true, size: true }).exec((result) => { const canvas = result[0]?.node; const layout = this.properties.layout as Layout | null; if (!canvas || !layout || !result[0].width) return; const dpr = wx.getWindowInfo ? wx.getWindowInfo().pixelRatio : wx.getSystemInfoSync().pixelRatio; canvas.width = result[0].width * dpr; canvas.height = result[0].height * dpr; const fitScale = result[0].width / layout.imageWidth; this.setData({ viewportWidth: result[0].width, viewportHeight: result[0].height, transform: { scale: fitScale, offsetX: 0, offsetY: 0 } }, () => { const ctx = canvas.getContext('2d'); ctx.resetTransform?.(); ctx.scale(dpr, dpr); this.render() }) }) },
  onReady() { this.initCanvas() },
  render() { const query = wx.createSelectorQuery().in(this); query.select('#wallCanvas').fields({ node: true, size: true }).exec((result) => { const canvas = result[0]?.node; const layout = this.properties.layout as Layout | null; if (!canvas) return; const ctx = canvas.getContext('2d'); ctx.clearRect(0, 0, result[0].width, result[0].height); if (!layout) return this.setData({ imageError: false }); const drawHolds = () => { const active = this.properties.activeHolds as Record<string, string>; for (const hold of layout.holds) { const [x, y] = imageToScreen([hold.x * layout.imageWidth, hold.y * layout.imageHeight], this.data.transform); ctx.beginPath(); ctx.arc(x, y, Math.max(8, hold.radius * layout.imageWidth * this.data.transform.scale), 0, Math.PI * 2); ctx.fillStyle = active[hold.id] === 'start' ? '#39a96b' : active[hold.id] === 'foot' ? '#d7ad18' : active[hold.id] === 'finish' ? '#8b55c7' : active[hold.id] === 'assist' ? '#ef8f39' : hold.kind === 'volume' ? '#ef8f39' : '#316eea'; ctx.fill() } }; const file = layout.displayImageFileId || layout.imageFileId; if (!file) { this.setData({ imageError: false }); return drawHolds() }; const draw = (path) => { const image = canvas.createImage(); image.onload = () => { this.setData({ imageError: false }); ctx.drawImage(image, 0, 0, result[0].width, result[0].height); drawHolds() }; image.onerror = () => { this.setData({ imageError: true }); drawHolds() }; image.src = path }; if (file.startsWith('cloud://')) downloadCloudImage(file).then(draw).catch(() => { this.setData({ imageError: true }); drawHolds() }); else draw(file) }) },
  onTouchStart(e: WechatMiniprogram.TouchEvent) { const touches = e.touches.map(t => ({ x: t.x, y: t.y })); if (!touches.length) return; const minScale = this.data.transform.scale; this.gesture = new GestureController(this.data.transform, minScale, minScale * 5); this.gesture.start(touches, Date.now()) },
  onTouchMove(e: WechatMiniprogram.TouchEvent) { if (!this.gesture || !e.touches.length) return; const result = this.gesture.move(e.touches.map(t => ({ x: t.x, y: t.y })), Date.now()); if (result.kind !== 'tap') { const layout = this.properties.layout as Layout | null; const transform = layout ? clampTransform(result.transform, this.data.viewportWidth, this.data.viewportHeight, layout.imageWidth, layout.imageHeight) : result.transform; this.setData({ transform }); this.render() } },
  onTouchEnd(e: WechatMiniprogram.TouchEvent) { if (this.gesture && e.changedTouches.length === 1) { const touch = e.changedTouches[0]; const result = this.gesture.move([{ x: touch.x, y: touch.y }], Date.now()); if (result.kind === 'tap') { const hold = this.hitTest(touch.x, touch.y); if (hold) this.triggerEvent('holdtap', { holdId: hold.id }) } } this.gesture?.end() },
  hitTest(x: number, y: number): Hold | undefined { const layout = this.properties.layout as Layout; const image = screenToImage([x, y], this.data.transform); const point = [image[0] / layout.imageWidth, image[1] / layout.imageHeight] as const; const direct = layout.holds.find(h => h.polygon?.length ? polygonHitTest(point, h) : circleHitTest(point, h)); return direct ?? nearestHold(point, layout.holds, 24 / this.data.transform.scale / layout.imageWidth) }
} })
