// @ts-nocheck
import type { Hold, Wall } from '../../domain/types.js'
import { circleHitTest, nearestHold, polygonHitTest } from '../../domain/geometry.js'
import { clampTransform, imageToScreen, screenToImage } from '../../domain/transform.js'
import { GestureController } from '../../domain/gesture.js'
import { getWallImageUrl } from '../../services/walls.js'
const COLORS = { start:'#3fb96a', foot:'#f0c24b', hand:'#3f7bd9', assist:'#f08e63', finish:'#8f5fd9' }
Component({
  properties: { wall: { type: Object, value: null, observer() { this.imageFile = ''; this.loadedImage = null; this.loadingImage = false; this.initCanvas() } }, activeHolds: { type: Object, value: {}, observer() { this.render() } } },
  data: { transform: { scale: 1, offsetX: 0, offsetY: 0 }, viewportWidth: 0, viewportHeight: 0, imageError: false },
  methods: {
    initCanvas() { const query = wx.createSelectorQuery().in(this); query.select('#wallCanvas').fields({ node: true, size: true }).exec((result) => { const canvas = result[0]?.node; const wall = this.properties.wall as Wall | null; if (!canvas || !wall || !result[0].width || !result[0].height) return; const dpr = wx.getWindowInfo ? wx.getWindowInfo().pixelRatio : wx.getSystemInfoSync().pixelRatio; canvas.width = result[0].width * dpr; canvas.height = result[0].height * dpr; const fitScale = Math.min(result[0].width / wall.imageWidth, result[0].height / wall.imageHeight); this.setData({ viewportWidth: result[0].width, viewportHeight: result[0].height, transform: { scale: fitScale, offsetX: (result[0].width - wall.imageWidth * fitScale) / 2, offsetY: (result[0].height - wall.imageHeight * fitScale) / 2 } }, () => { const ctx = canvas.getContext('2d'); ctx.resetTransform?.(); ctx.scale(dpr, dpr); this.render() }) }) },
    onReady() { this.initCanvas() },
    render() { const query = wx.createSelectorQuery().in(this); query.select('#wallCanvas').fields({ node: true, size: true }).exec((result) => { const canvas = result[0]?.node; const wall = this.properties.wall as Wall | null; if (!canvas || !wall) return; const ctx = canvas.getContext('2d'); const width = result[0].width, height = result[0].height; ctx.clearRect(0, 0, width, height); const active = this.properties.activeHolds || {}; const byHold = Object.keys(active).reduce((map, role) => { const value = active[role]; if (Array.isArray(value)) value.forEach(id => { map[id] = role }); else if (typeof value === 'string') map[value] = role; return map }, {}); const drawHolds = () => { for (const hold of wall.holds) { const role = byHold[hold.id]; if (!role) continue; const color = COLORS[role]; const path = () => { ctx.beginPath(); if (hold.polygon?.length >= 3) { hold.polygon.forEach((point, i) => { const p = imageToScreen([point[0] * wall.imageWidth, point[1] * wall.imageHeight], this.data.transform); i ? ctx.lineTo(p[0], p[1]) : ctx.moveTo(p[0], p[1]) }); ctx.closePath() } else { const p = imageToScreen([hold.x * wall.imageWidth, hold.y * wall.imageHeight], this.data.transform); ctx.arc(p[0], p[1], Math.max(8, hold.radius * wall.imageWidth * this.data.transform.scale), 0, Math.PI * 2) } }; path(); ctx.fillStyle = `${color}55`; ctx.fill(); ctx.lineWidth = 3; ctx.strokeStyle = color; ctx.stroke(); path(); ctx.lineWidth = 1; ctx.strokeStyle = '#fff'; ctx.stroke() } }; const file = wall.displayImageFileId || wall.imageFileId || ''; if (!file) return drawHolds(); const drawImage = (image) => { ctx.drawImage(image, this.data.transform.offsetX, this.data.transform.offsetY, wall.imageWidth * this.data.transform.scale, wall.imageHeight * this.data.transform.scale); drawHolds() }; if (this.imageFile === file && this.loadedImage) return drawImage(this.loadedImage); if (this.loadingImage && this.imageFile === file) return; this.imageFile = file; this.loadingImage = true; const load = (path) => { const image = canvas.createImage(); image.onload = () => { this.loadedImage = image; this.loadingImage = false; this.setData({ imageError: false }); this.render() }; image.onerror = () => { this.loadingImage = false; this.loadedImage = null; this.setData({ imageError: true }); drawHolds() }; image.src = path }; if (file.startsWith('cloud://')) getWallImageUrl(file).then(load).catch(() => { this.loadingImage = false; this.setData({ imageError: true }); drawHolds() }); else load(file) }) },
    onTouchStart(e) { const touches = e.touches.map(t => ({ x: t.x, y: t.y })); if (!touches.length) return; const minScale = this.data.transform.scale; this.gesture = new GestureController(this.data.transform, minScale, minScale * 5); this.gesture.start(touches, Date.now()) },
    onTouchMove(e) { if (!this.gesture || !e.touches.length) return; const result = this.gesture.move(e.touches.map(t => ({ x: t.x, y: t.y })), Date.now()); if (result.kind !== 'tap') { const wall = this.properties.wall as Wall | null; const transform = wall ? clampTransform(result.transform, this.data.viewportWidth, this.data.viewportHeight, wall.imageWidth, wall.imageHeight) : result.transform; this.setData({ transform }); this.render() } },
    onTouchEnd(e) { if (this.gesture && e.changedTouches.length === 1) { const touch = e.changedTouches[0]; const result = this.gesture.move([{ x: touch.x, y: touch.y }], Date.now()); if (result.kind === 'tap') { const hold = this.hitTest(touch.x, touch.y); if (hold) this.triggerEvent('holdtap', { holdId: hold.id }) } } this.gesture?.end() },
    hitTest(x, y): Hold | undefined { const wall = this.properties.wall as Wall; const image = screenToImage([x, y], this.data.transform); const point = [image[0] / wall.imageWidth, image[1] / wall.imageHeight] as const; const direct = wall.holds.find(h => h.polygon?.length ? polygonHitTest(point, h) : circleHitTest(point, h)); return direct ?? nearestHold(point, wall.holds, 24 / this.data.transform.scale / wall.imageWidth) },
  },
})
