// @ts-nocheck
import type { Hold, Wall } from '../../domain/types.js'
import { circleHitTest, nearestHold, polygonHitTest } from '../../domain/geometry.js'
import { clampTransform, imageToScreen, screenToImage } from '../../domain/transform.js'
import { GestureController } from '../../domain/gesture.js'
import { wallImagePath, invalidateWallImage } from '../../services/image-cache.js'
const COLORS = { start:'#3fb96a', foot:'#f0c24b', hand:'#3f7bd9', assist:'#f08e63', finish:'#8f5fd9' }
Component({
  properties: { wall: { type: Object, value: null, observer(wall) { const key = wall ? `${wall.id}:${wall.displayImageFileId || wall.imageFileId}:${wall.imageWidth}:${wall.imageHeight}` : ''; if (key && key === this.wallKey) { this.render(); return } this.wallKey = key; this.imageEpoch = (this.imageEpoch || 0) + 1; this.imageRetries = 0; this.imageFile = ''; this.loadedImage = null; this.loadingImage = false; this.initCanvas() } }, annotation: {type:Boolean,value:false}, activeHolds: { type: Object, value: {}, observer() { this.render() } } },
  data: { transform: { scale: 1, offsetX: 0, offsetY: 0 }, viewportWidth: 0, viewportHeight: 0, imageError: false },
  lifetimes: { ready() { this.detachedCanvas = false; this.initCanvas() }, detached() { this.imageEpoch = (this.imageEpoch || 0) + 1; this.detachedCanvas = true; if (this.renderTimer) clearTimeout(this.renderTimer) } },
  methods: {
    initCanvas() { const query = wx.createSelectorQuery().in(this); query.select('#wallCanvas').fields({ node: true, size: true }).exec((result) => { const canvas = result[0]?.node; const wall = this.properties.wall as Wall | null; if (!canvas || !wall || !result[0].width || !result[0].height) return; const dpr = wx.getWindowInfo ? wx.getWindowInfo().pixelRatio : wx.getSystemInfoSync().pixelRatio; canvas.width = result[0].width * dpr; canvas.height = result[0].height * dpr; const fitScale = Math.min(result[0].width / wall.imageWidth, result[0].height / wall.imageHeight); this.fitScale = fitScale; this.setData({ viewportWidth: result[0].width, viewportHeight: result[0].height, transform: { scale: fitScale, offsetX: (result[0].width - wall.imageWidth * fitScale) / 2, offsetY: (result[0].height - wall.imageHeight * fitScale) / 2 } }, () => { const ctx = canvas.getContext('2d'); ctx.resetTransform?.(); ctx.scale(dpr, dpr); this.render() }) }) },
    render() { if (this.renderTimer || this.detachedCanvas) return; this.renderTimer = setTimeout(() => { this.renderTimer = undefined; if (!this.detachedCanvas) this.draw() }, 16) },
    draw() { const query = wx.createSelectorQuery().in(this); query.select('#wallCanvas').fields({ node: true, size: true }).exec((result) => { const canvas = result[0]?.node; const wall = this.properties.wall as Wall | null; if (!canvas || !wall) return; const ctx = canvas.getContext('2d'); const width = result[0].width, height = result[0].height; ctx.clearRect(0, 0, width, height); const active = this.properties.activeHolds || {}; const byHold = Object.keys(active).reduce((map, role) => { const value = active[role]; if (Array.isArray(value)) value.forEach(id => { map[id] = role }); else if (typeof value === 'string') map[role] = value; return map }, {}); const drawHolds = () => { for (const hold of wall.holds) { const role = byHold[hold.id] || (this.properties.annotation ? 'hand' : undefined); if (!role) continue; const color = COLORS[role]; const path = () => { ctx.beginPath(); if (hold.polygon?.length >= 3) { hold.polygon.forEach((point, i) => { const p = imageToScreen([point[0] * wall.imageWidth, point[1] * wall.imageHeight], this.data.transform); i ? ctx.lineTo(p[0], p[1]) : ctx.moveTo(p[0], p[1]) }); ctx.closePath() } else { const p = imageToScreen([hold.x * wall.imageWidth, hold.y * wall.imageHeight], this.data.transform); ctx.arc(p[0], p[1], Math.max(8, hold.radius * wall.imageWidth * this.data.transform.scale), 0, Math.PI * 2) } }; path(); ctx.fillStyle = `${color}55`; ctx.fill(); ctx.lineWidth = 3; ctx.strokeStyle = color; ctx.stroke(); path(); ctx.lineWidth = 1; ctx.strokeStyle = '#fff'; ctx.stroke() } }; const file = wall.displayImageFileId || wall.imageFileId || ''; if (!file) return drawHolds(); const drawImage = (image) => { ctx.drawImage(image, this.data.transform.offsetX, this.data.transform.offsetY, wall.imageWidth * this.data.transform.scale, wall.imageHeight * this.data.transform.scale); drawHolds() }; if (this.imageFile === file && this.loadedImage) return drawImage(this.loadedImage); if (this.loadingImage && this.imageFile === file) return; this.imageFile = file; this.loadingImage = true; const epoch = this.imageEpoch; const current = () => !this.detachedCanvas && epoch === this.imageEpoch && this.imageFile === file; const load = (path) => { const image = canvas.createImage(); image.onload = () => { if (!current()) return; this.imageRetries = 0; this.loadedImage = image; this.loadingImage = false; this.setData({ imageError: false }); this.render() }; image.onerror = () => { if (!current()) return; if (!this.imageRetries) { this.imageRetries = 1; invalidateWallImage(file); this.loadingImage = false; this.render(); return } this.loadingImage = false; this.loadedImage = null; this.setData({ imageError: true }); drawHolds() }; image.src = path }; wallImagePath(file).then(path => { if (current()) load(path) }).catch(() => { if (!current()) return; this.loadingImage = false; this.setData({ imageError: true }); drawHolds() }) }) },
    onTouchStart(e) { const touches = e.touches.map(t => ({ x: t.x, y: t.y })); if (!touches.length) return; this.touchMoved = false; this.hadMultipleTouches = touches.length > 1; const minScale = this.fitScale || this.data.transform.scale; this.gesture = new GestureController(this.data.transform, minScale, minScale * 5); this.gesture.start(touches, Date.now()) },
    onTouchMove(e) { if (!this.gesture || !e.touches.length) return; if (e.touches.length > 1) this.hadMultipleTouches = true; const result = this.gesture.move(e.touches.map(t => ({ x: t.x, y: t.y })), Date.now()); if (result.kind !== 'tap') { this.touchMoved = true; const wall = this.properties.wall as Wall | null; const transform = wall ? clampTransform(result.transform, this.data.viewportWidth, this.data.viewportHeight, wall.imageWidth, wall.imageHeight) : result.transform; this.setData({ transform }); this.render() } },
    onTouchEnd(e) { if (this.gesture && e.changedTouches.length === 1) { const touch = e.changedTouches[0]; const result = this.gesture.move([{ x: touch.x, y: touch.y }], Date.now()); if (result.kind === 'tap' && !this.touchMoved && !this.hadMultipleTouches) { const wall = this.properties.wall; const p = screenToImage([touch.x, touch.y], this.data.transform); const point = {x:p[0]/wall.imageWidth,y:p[1]/wall.imageHeight}; const hold = this.hitTest(touch.x, touch.y); if (hold) this.triggerEvent('holdtap', { holdId: hold.id }); if (point.x >= 0 && point.x <= 1 && point.y >= 0 && point.y <= 1) this.triggerEvent('imagepoint', {...point, holdId:hold?.id}) } } this.gesture?.end(); this.gesture = undefined; if (e.touches?.length) { const touches = e.touches.map(t => ({x:t.x,y:t.y})); this.gesture = new GestureController(this.data.transform, this.fitScale || 1, (this.fitScale || 1) * 5); this.gesture.start(touches, Date.now()); this.touchMoved = true; this.hadMultipleTouches = true } },
    onTouchCancel() { this.gesture = undefined; this.touchMoved = true },
    hitTest(x, y): Hold | undefined { const wall = this.properties.wall as Wall; const image = screenToImage([x, y], this.data.transform); const point = [image[0] / wall.imageWidth, image[1] / wall.imageHeight] as const; const direct = wall.holds.find(h => h.polygon?.length ? polygonHitTest(point, h) : circleHitTest(point, h)); return direct ?? nearestHold(point, wall.holds, 24 / this.data.transform.scale / wall.imageWidth) },
  },
})
