// @ts-nocheck
import { demoWall } from '../../../data/demo.js'
import { ProblemEditor } from '../../../domain/editor.js'
import { getProblem, saveProblem, updateProblem } from '../../../services/problems.js'
import { getWall } from '../../../services/walls.js'
import { currentUserId } from '../../../services/users.js'
let wall=demoWall,wallId='wall_demo',problemId='',draftKey=`problemDraft:${wallId}`,editor=new ProblemEditor({}),saved={}
const roles=[{id:'start',label:'Start',color:'#39a96b'},{id:'foot',label:'Foot',color:'#d7ad18'},{id:'hand',label:'Hand',color:'#316eea'},{id:'assist',label:'Assist',color:'#ef8f39'},{id:'finish',label:'Finish',color:'#8b55c7'}],footRules=['feet_follow','specified','all'],grades=Array.from({length:13},(_,i)=>`V${i}`),labels={feet_follow:'跟随手点',specified:'指定脚点',all:'全墙脚点'},hints={feet_follow:'手类点可踩，黄色 Foot 只能脚踩',specified:'脚只能踩线路中的黄色 Foot',all:'当前墙面所有岩点均可作为脚点'}
const persist=page=>wx.setStorageSync(draftKey,{name:page.data.name,description:page.data.description,angle:page.data.angle,grade:page.data.grade,footRule:page.data.footRule,holds:editor.value().holds})
Page({data:{wall,problemId:'',editing:false,angles:[20,25,30,35,40,45],grades,angle:35,angleIndex:3,grade:'V4',gradeIndex:4,roles,selectedRole:'hand',footRules,footRuleIndex:0,footRule:'feet_follow',footRuleLabel:labels.feet_follow,footRuleHint:hints.feet_follow,name:'',description:'',selected:{}},async onLoad(options){problemId=options.problemId||options.id||'';if(problemId){const problem=await getProblem(problemId);wallId=problem.wallId;saved=problem}else{wallId=options.wallId||wallId;draftKey=`problemDraft:${wallId}`;saved=wx.getStorageSync(draftKey)||{}}editor=new ProblemEditor(saved.holds||{});wall=await getWall(wallId);const angle=saved.angle||wall.angleOptions[0],grade=saved.grade||'V4',footRule=saved.footRule||'feet_follow';this.setData({wall,problemId,editing:Boolean(problemId),angles:wall.angleOptions,selected:editor.value().holds,name:saved.name||'',description:saved.description||'',footRule,footRuleIndex:footRules.indexOf(footRule),footRuleLabel:labels[footRule],footRuleHint:hints[footRule],angle,angleIndex:wall.angleOptions.indexOf(angle),grade,gradeIndex:grades.indexOf(grade)})},selectRole(e){this.setData({selectedRole:e.currentTarget.dataset.role})},onHoldTap(e){editor.toggle(e.detail.holdId,this.data.selectedRole);this.setData({selected:editor.value().holds});persist(this)},selectHold(e){editor.toggle(e.currentTarget.dataset.id,this.data.selectedRole);this.setData({selected:editor.value().holds});persist(this)},undo(){editor.undo();this.setData({selected:editor.value().holds});persist(this)},clear(){editor.clear();this.setData({selected:editor.value().holds});persist(this)},setName(e){this.setData({name:e.detail.value});persist(this)},setDescription(e){this.setData({description:e.detail.value});persist(this)},selectAngle(e){const angleIndex=Number(e.detail.value);this.setData({angle:Number(this.data.angles[angleIndex]),angleIndex});persist(this)},selectGrade(e){const gradeIndex=Number(e.detail.value);this.setData({grade:grades[gradeIndex],gradeIndex});persist(this)},selectFootRule(e){const index=Number(e.detail.value),footRule=footRules[index];this.setData({footRule,footRuleIndex:index,footRuleLabel:labels[footRule],footRuleHint:hints[footRule]});persist(this)},save(){if(!currentUserId())return wx.showToast({title:'登录中，请稍后再试',icon:'none'});const draft={name:this.data.name,description:this.data.description,angle:this.data.angle,grade:this.data.grade,footRule:this.data.footRule,holds:editor.value().holds},request=problemId?updateProblem(problemId,draft):saveProblem(wallId,draft);request.then(result=>{wx.removeStorageSync(draftKey);wx.showToast({title:`${problemId?'已更新':'已保存'} ${result.number}`});setTimeout(()=>wx.navigateBack(),500)}).catch(()=>wx.showToast({title:'保存失败，草稿已保留',icon:'none'}))}})
