// @ts-nocheck
import { ProblemEditor } from '../../../../src/domain/editor.js'
import { demoLayout } from '../../../../src/data/demo.js'
import { saveProblem } from '../../../services/problems.js'
import { getCachedLayout } from '../../../services/layouts.js'
import { currentUserId } from '../../../services/users.js'
let layout=demoLayout;let wallId='wall_demo';let layoutId=demoLayout.id;let draftKey=`problemDraft:${layoutId}`
const roles=[{id:'start',label:'Start',color:'#39a96b'},{id:'foot',label:'Foot',color:'#d7ad18'},{id:'hand',label:'Hand',color:'#316eea'},{id:'assist',label:'Assist',color:'#ef8f39'},{id:'finish',label:'Finish',color:'#8b55c7'}]
const footRules=['feet_follow','specified','all'];const labels={feet_follow:'手脚同点',specified:'指定脚点',all:'全墙脚点'};const hints={feet_follow:'手类点可踩，黄色 Foot 只能脚踩',specified:'脚只能踩黄色 Foot',all:'当前 Layout 所有岩点均可作为脚点'}
let saved=wx.getStorageSync(draftKey)||{};let editor=new ProblemEditor(saved.holds||saved)
Page({data:{layout,roles,selectedRole:'hand',footRules,footRuleIndex:0,footRule:'feet_follow',footRuleLabel:labels.feet_follow,footRuleHint:hints.feet_follow,name:saved.name||'',description:saved.description||'',selected:editor.value().holds},onLoad(options){wallId=options.wallId||wallId;layoutId=options.layoutId||layoutId;draftKey=`problemDraft:${layoutId}`;saved=wx.getStorageSync(draftKey)||{};getCachedLayout(layoutId,1).then(next=>{layout=next;editor=new ProblemEditor(saved.holds||next.holds.reduce((all,h)=>({...all,[h.id]:[]}),{}));this.setData({layout,selected:editor.value().holds,name:saved.name||'',description:saved.description||'',footRule:saved.footRule||'feet_follow'})}).catch(()=>{})},selectRole(e){this.setData({selectedRole:e.currentTarget.dataset.role})},onHoldTap(e){editor.toggle(e.detail.holdId,this.data.selectedRole);this.persist();this.setData({selected:editor.value().holds})},selectHold(e){this.onHoldTap({detail:{holdId:e.currentTarget.dataset.id}})},selectFootRule(e){const index=Number(e.detail.value);this.setData({footRuleIndex:index,footRule:footRules[index],footRuleLabel:labels[footRules[index]],footRuleHint:hints[footRules[index]]});this.persist()},setName(e){this.setData({name:e.detail.value});this.persist()},setDescription(e){this.setData({description:e.detail.value});this.persist()},undo(){editor.undo();this.persist();this.setData({selected:editor.value().holds})},clear(){wx.showModal({title:'清空线路？',content:'将移除当前线路的全部角色设置。',success:result=>{if(result.confirm){editor.clear();this.persist();this.setData({selected:editor.value().holds})}}})},persist(){wx.setStorageSync(draftKey,{holds:editor.value().holds,name:this.data.name,description:this.data.description,footRule:this.data.footRule})},save(){if(!currentUserId())return wx.showToast({title:'登录中，请稍后再试',icon:'none'});saveProblem(wallId,layoutId,{name:this.data.name,description:this.data.description,angle:35,grade:'V4',footRule:this.data.footRule,holds:editor.value().holds}).then(result=>{wx.removeStorageSync(draftKey);wx.showToast({title:`已保存 ${result.number}`});setTimeout(()=>wx.navigateBack(),500)}).catch(()=>wx.showToast({title:'保存失败，草稿已保留',icon:'none'}))}})
