from typing import Any, Protocol


Document = dict[str, Any]


class CruxRepository(Protocol):
    def insert_user(self, user: Document) -> None: ...

    def find_user(self, user_id: str) -> Document | None: ...

    def insert_admin(self, admin: Document) -> None: ...

    def find_admin_by_email(self, email: str) -> Document | None: ...

    def find_admin_by_user_id(self, user_id: str) -> Document | None: ...

    def update_admin_password(self, email: str, password_hash: str, updated_at: int) -> None: ...

    def list_layouts(self, wall_id: str) -> list[Document]: ...

    def insert_layout(self, layout: Document) -> None: ...

    def find_problem(self, problem_id: str) -> Document | None: ...

    def delete_problem(self, problem_id: str) -> None: ...

    def delete_wall(self, wall_id: str) -> None: ...
