from typing import Any, Protocol


Document = dict[str, Any]


class CruxRepository(Protocol):
    def insert_user(self, user: Document) -> None: ...

    def find_user(self, user_id: str) -> Document | None: ...

    def insert_admin(self, admin: Document) -> None: ...

    def find_admin_by_email(self, email: str) -> Document | None: ...

    def find_admin_by_user_id(self, user_id: str) -> Document | None: ...

    def update_admin_password(self, email: str, password_hash: str, updated_at: int) -> None: ...

    def insert_wall(self, wall: Document) -> None: ...

    def replace_wall(self, wall: Document) -> None: ...

    def find_wall(self, wall_id: str) -> Document | None: ...

    def list_walls(self) -> list[Document]: ...

    def delete_wall(self, wall_id: str) -> None: ...

    def insert_problem(self, problem: Document) -> None: ...

    def find_problem(self, problem_id: str) -> Document | None: ...

    def list_problems(self) -> list[Document]: ...

    def delete_problem(self, problem_id: str) -> None: ...

    def count_problems_for_wall(self, wall_id: str) -> int: ...
