import './styles/tokens.css'
import './styles/base.css'
import './styles/device.css'
import './styles/editor.css'
import './styles/responsive.css'
import ProblemEditor from '../../miniprogram/domain/editor.js'
import type { FootRule, Grade, Hold, HoldRole, Problem, Wall } from '../../miniprogram/domain/types.js'
import { WallHoldEditor } from './wall-hold-editor.js'
import { PreviewStore } from './preview-store.js'
import { LocalApiClient } from './api.js'
import { WallCanvasView, ROLE_COLORS } from './wall-canvas.js'
import { DraftCanvasView, type DraftMode } from './draft-canvas.js'
import { DETECT_ROI_FALLBACK_MESSAGE, type Roi } from './auto-detect.js'
import { holdsForPersistence } from './candidate-editor.js'

export const DEFAULT_DETECT_ROI: Roi = { x: 0, y: 0, width: 1, height: 1 }
const validRoi = (r:Roi) => Number.isFinite(r.x)&&Number.isFinite(r.y)&&Number.isFinite(r.width)&&Number.isFinite(r.height)&&r.x>=0&&r.y>=0&&r.width>0&&r.height>0&&r.x+r.width<=1&&r.y+r.height<=1
export const detectRoiValidationMessage = (r:Roi) => validRoi(r) ? undefined : DETECT_ROI_FALLBACK_MESSAGE
export const normalizeDetectRoi = (r:Roi):Roi => validRoi(r) ? {...r} : {...DEFAULT_DETECT_ROI}
export const resetDetectRoi = ():Roi => ({...DEFAULT_DETECT_ROI})
export const shouldReplaceDetectedHolds = (h:Hold[]|null|undefined):h is Hold[] => Boolean(h?.length)
export const createAutoDetectController = (detect:()=>Promise<Hold[]>, replace:(h:Hold[])=>void, active=()=>true, done?:()=>void) => {
  let processing=false, generation=0
  return { get processing(){return processing}, cancel(){generation++;processing=false}, async run(){if(processing)return false;processing=true;const current=generation;try{const holds=await detect();if(current!==generation||!active()||!shouldReplaceDetectedHolds(holds))return false;replace(holds);done?.();return true}catch{return false}finally{processing=false}} }
}

const root=document.querySelector<HTMLElement>('#app')!, store=new PreviewStore(), api=new LocalApiClient()
let authenticated=false, loginError='', panel:'home'|'drafts'|'new-wall'|'my-walls'|'my-problems'='home', expandedWall='', managementError=''
const thumb='<i class="thumb"></i>', back='<button class="back-button" data-back>‹</button>'
const roles:HoldRole[]=['start','foot','hand','assist','finish']
const roleLabels:Record<HoldRole,string>={start:'起步',foot:'脚点',hand:'手点',assist:'辅助',finish:'终点'}
const footLabels:Record<FootRule,string>={feet_follow:'手脚同点',specified:'指定脚点',all:'全墙脚点'}
const grades:Grade[]=['V0','V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12']

type ProblemCtx={wall:Wall;editor:ProblemEditor;role:HoldRole;angle:number;grade:Grade;footRule:FootRule;name:string;description:string;undo:number;canvas?:WallCanvasView;saved?:string;toast?:string}
type WallCtx={wall:Wall;editor:WallHoldEditor;mode:DraftMode;selected:string|null;kind:'hold'|'volume';dirty:boolean;canvas?:DraftCanvasView;toast?:string;published:boolean}
type DetailCtx={problem:Problem;wall:Wall;canvas?:WallCanvasView}
let problemCtx:ProblemCtx|null=null, wallCtx:WallCtx|null=null, detailCtx:DetailCtx|null=null

const renderLogin=()=>{root.innerHTML=`<div class="device"><main class="login-page"><div class="login-card"><h1>管理员登录</h1><label>邮箱<input id="email"></label><label>密码<input id="password" type="password"></label><button data-login>登录</button><p>${loginError}</p></div></main></div>`;root.querySelector<HTMLButtonElement>('[data-login]')!.onclick=async()=>{try{await api.login((root.querySelector('#email') as HTMLInputElement).value,(root.querySelector('#password') as HTMLInputElement).value);await store.useApi(api);authenticated=true;void render()}catch(e){loginError=(e as Error).message;renderLogin()}}}

const openProblemEditor=async(wallId:string)=>{const wall=await store.session.getWall(wallId);problemCtx={wall,editor:new ProblemEditor(),role:'hand',angle:wall.angleOptions[0]??20,grade:'V4',footRule:'feet_follow',name:'',description:'',undo:0};store.navigate({name:'problem-editor',wallId})}
const renderProblemEditor=()=>{const c=problemCtx!;root.innerHTML=`<div class="device"><main><button data-exit>‹</button><div class="editor-head"><h1>新建线路</h1><p>${c.wall.name}</p></div><div class="chips">${c.wall.angleOptions.map(x=>`<button data-angle="${x}">${x}°</button>`).join('')}</div><div class="chips">${grades.map(x=>`<button data-grade="${x}">${x}</button>`).join('')}</div><div class="chips">${Object.entries(footLabels).map(([x,l])=>`<button data-foot="${x}">${l}</button>`).join('')}</div><div id="editor-canvas"></div><div class="role-toolbar">${roles.map(x=>`<button data-role="${x}"><i style="background:${ROLE_COLORS[x]}"></i>${roleLabels[x]}</button>`).join('')}</div><div class="editor-actions"><button data-undo>撤销</button><button data-clear>清空</button><button data-save>保存线路</button></div><div class="field"><input id="problem-name" placeholder="线路名称"><textarea id="problem-description" placeholder="线路说明"></textarea></div><p class="editor-toast">${c.toast??''}</p></main></div>`;root.querySelector('[data-exit]')!.addEventListener('click',()=>{c.canvas?.destroy();problemCtx=null;store.navigate({name:'wall',wallId:c.wall.id})});root.querySelectorAll<HTMLElement>('[data-angle]').forEach(x=>x.onclick=()=>{c.angle=Number(x.dataset.angle)});root.querySelectorAll<HTMLElement>('[data-grade]').forEach(x=>x.onclick=()=>{c.grade=x.dataset.grade as Grade});root.querySelectorAll<HTMLElement>('[data-foot]').forEach(x=>x.onclick=()=>{c.footRule=x.dataset.foot as FootRule});root.querySelectorAll<HTMLElement>('[data-role]').forEach(x=>x.onclick=()=>{c.role=x.dataset.role as HoldRole});root.querySelector('[data-undo]')!.addEventListener('click',()=>c.editor.undo());root.querySelector('[data-clear]')!.addEventListener('click',()=>c.editor.clear());root.querySelector('[data-save]')!.addEventListener('click',async()=>{c.name=(root.querySelector('#problem-name') as HTMLInputElement).value;c.description=(root.querySelector('#problem-description') as HTMLTextAreaElement).value;try{const p=await store.session.createProblem(c.wall.id,{angle:c.angle,grade:c.grade,footRule:c.footRule,name:c.name||undefined,description:c.description||undefined,holds:c.editor.value().holds});c.saved=p.number;c.toast=`已保存线路 ${p.number}`}catch(e){c.toast=`保存失败：${(e as Error).message}`}renderProblemEditor()});c.canvas=new WallCanvasView(root.querySelector('#editor-canvas') as HTMLElement,{imageUrl:c.wall.imageFileId,imageWidth:c.wall.imageWidth,imageHeight:c.wall.imageHeight,holds:c.wall.holds,getAssignments:()=>c.editor.value().holds,getSelectedRole:()=>c.role,onTapHold:id=>{c.editor.toggle(id,c.role);c.canvas?.redraw()}})}

const openWallEditor=async(wallId:string)=>{const wall=await store.session.getWall(wallId);wallCtx={wall,editor:new WallHoldEditor(wall.holds),mode:'add',selected:null,kind:'hold',dirty:false,published:false};store.navigate({ name: 'wall-editor', wallId })}
const renderWallEditor=()=>{const c=wallCtx!,holds=c.editor.value();root.innerHTML=`<div class="device"><main><button data-exit>‹</button><div class="editor-head"><h1>标注墙面</h1><p>${c.wall.name} · ${holds.length} 个岩点</p></div><div class="draft-toolbar"><button data-mode="add">添加</button><button data-mode="move">移动</button><button data-mode="delete">删除</button><button data-undo>撤销</button><button data-clear>清空</button></div><div class="draft-toolbar"><button data-kind="hold">岩点</button><button data-kind="volume">体积</button><span>双指缩放 · 单指平移</span></div><div id="draft-canvas"></div><div class="editor-actions"><button data-save-wall>保存草稿</button><button data-publish-wall>发布墙面</button></div><p class="editor-toast">${c.toast??''}</p></main></div>`;root.querySelector('[data-exit]')!.addEventListener('click',()=>{c.canvas?.destroy();wallCtx=null;panel='drafts';store.navigate({name:'create'})});root.querySelectorAll<HTMLElement>('[data-mode]').forEach(x=>x.onclick=()=>{c.mode=x.dataset.mode as DraftMode;c.selected=null;renderWallEditor()});root.querySelectorAll<HTMLElement>('[data-kind]').forEach(x=>x.onclick=()=>{c.kind=x.dataset.kind as 'hold'|'volume'});root.querySelector('[data-undo]')!.addEventListener('click',()=>{c.editor.undo();c.dirty=true;renderWallEditor()});root.querySelector('[data-clear]')!.addEventListener('click',()=>{c.editor=new WallHoldEditor([]);c.dirty=true;renderWallEditor()});root.querySelector('[data-save-wall]')!.addEventListener('click',async()=>{c.wall=await store.session.updateWallHolds(c.wall.id,holdsForPersistence(c.editor.value()));c.dirty=false;c.toast='草稿已保存';renderWallEditor()});root.querySelector('[data-publish-wall]')!.addEventListener('click',async()=>{try{c.wall=await store.session.publishWall(c.wall.id,holdsForPersistence(c.editor.value()));c.published=true;c.toast='墙面已公开并锁定'}catch(e){c.toast=`发布失败：${(e as Error).message}`}renderWallEditor()});c.canvas=new DraftCanvasView(root.querySelector('#draft-canvas') as HTMLElement,{imageUrl:c.wall.imageFileId,imageWidth:c.wall.imageWidth,imageHeight:c.wall.imageHeight,holds,mode:c.mode,selectedId:c.selected,onAddHold:p=>{c.editor.add({x:p[0],y:p[1],radius:c.kind==='volume'?.05:.018,kind:c.kind});c.dirty=true;renderWallEditor()},onMoveStart:()=>c.editor.beginChange(),onMoveHold:(id,p)=>{c.editor.setPosition(id,p[0],p[1]);c.dirty=true;c.canvas?.setState(c.editor.value(),c.mode,c.selected)},onDeleteHold:id=>{c.editor.remove(id);c.dirty=true;renderWallEditor()},onSelectHold:id=>{c.selected=id;c.canvas?.setState(c.editor.value(),c.mode,c.selected)}})}

const openDetail=async(problemId:string)=>{const problem=(await store.session.listProblems()).find(x=>x.id===problemId);if(!problem)return;detailCtx={problem,wall:await store.session.getWall(problem.wallId)};store.navigate({name:'problem-detail',problemId})}
const renderDetail=()=>{const c=detailCtx!;root.innerHTML=`<div class="device"><main><button data-exit>‹</button><h1>${c.problem.name||c.problem.number}</h1><p>${c.wall.name} · ${c.problem.angle}° · ${c.problem.grade}</p><div id="detail-canvas"></div></main></div>`;root.querySelector('[data-exit]')!.addEventListener('click',()=>{c.canvas?.destroy();detailCtx=null;store.navigate({name:'wall',wallId:c.problem.wallId})});c.canvas=new WallCanvasView(root.querySelector('#detail-canvas') as HTMLElement,{imageUrl:c.wall.imageFileId,imageWidth:c.wall.imageWidth,imageHeight:c.wall.imageHeight,holds:c.wall.holds,getAssignments:()=>c.problem.holds,getSelectedRole:()=>null,onTapHold:()=>{}})}

const imageDimensions=(file:File)=>new Promise<{width:number;height:number}>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=reject;image.src=URL.createObjectURL(file)})
const render=async()=>{if(!authenticated){renderLogin();return}const route=store.state.route;if(route.name==='wall-editor'){if(!wallCtx)await openWallEditor(route.wallId);renderWallEditor();return}if(route.name==='problem-editor'){if(!problemCtx)await openProblemEditor(route.wallId);renderProblemEditor();return}if(route.name==='problem-detail'){if(!detailCtx)await openDetail(route.problemId);if(detailCtx)renderDetail();return}const tab=route.name==='create'?'create':route.name==='me'?'me':'browse', publicWalls=await store.session.listWalls(), mine=await store.session.listMyWalls(), problems=await store.session.listProblems(), drafts=mine.filter(wall=>wall.visibility === 'private'), selected=route.name==='wall'?publicWalls.find(w=>w.id===route.wallId):undefined
const browse=selected?`${back}<h1>${selected.name}</h1><p>${selected.holds.length} 个岩点</p><button data-new-problem="${selected.id}">新建线路</button>${problems.filter(p=>p.wallId===selected.id).map(p=>`<button class="problem-row" data-problem="${p.id}"><b>${p.number}</b><em>${p.name||'未命名线路'} · ${p.grade}</em></button>`).join('')}`:`<h1>线路</h1><p>选择一面公开墙面。</p>${publicWalls.map(w=>`<button class="wall-card" data-wall="${w.id}">${thumb}<span><b>${w.name}</b><em>${w.holds.length} 个岩点 · ${problems.filter(p=>p.wallId===w.id).length} 条线路</em></span></button>`).join('')}`
const create=panel==='new-wall'?`${back}<h1>新建墙面</h1><input id="wall-name" placeholder="墙面名称"><input id="wall-image" type="file"><p id="wall-error"></p><button data-create-wall>创建草稿墙面</button>`:panel==='drafts'?`${back}<h1>我的草稿</h1>${drafts.map(w=>`<button class="mine-card" data-edit-wall="${w.id}">${thumb}<b>${w.name}</b><em>${w.holds.length} 个岩点</em></button>`).join('')||'<p>没有私有墙面草稿</p>'}`:`<h1>创建</h1><button data-panel="new-wall">新建墙面</button><button data-panel="drafts">我的草稿 · ${drafts.length}</button><p>发布即公开并锁定。</p>`
const cards=mine.map(w=>`<article class="wall-management-card">${thumb}<span><b>${w.name}</b><em>${w.holds.length} 个岩点</em></span><small>${w.visibility==='public'?'公开':'私有'}</small><button data-delete-wall="${w.id}">删除</button></article>`).join(''),groups=mine.filter(w=>w.visibility==='public').map(w=>{const ps=problems.filter(p=>p.wallId===w.id),open=expandedWall===w.id;return `<article><button data-expand="${w.id}"><b>${w.name}</b><em>${ps.length} 条线路</em></button>${open?ps.map(p=>`<div class="problem-row"><b>${p.number}</b><button data-delete-problem="${p.id}">删除</button></div>`).join(''):''}</article>`}).join('')
const me=panel==='my-walls'?`${back}<h1>我的墙面</h1>${managementError?`<p class="editor-toast">${managementError}</p>`:''}${cards}`:panel==='my-problems'?`${back}<h1>我的线路</h1>${groups}`:`<h1>我的</h1><button data-panel="my-walls">我的墙面 · ${mine.length}</button><button data-panel="my-problems">我的线路 · ${problems.length}</button>`
root.innerHTML=`<div class="device"><header><small>CRUXSET</small></header><main>${tab==='browse'?browse:tab==='create'?create:me}</main><nav>${(['browse','create','me'] as const).map(x=>`<button data-tab="${x}">${x==='browse'?'线路':x==='create'?'创建':'我的'}</button>`).join('')}</nav></div>`
root.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>{panel='home';store.navigate({name:b.dataset.tab as 'browse'|'create'|'me'})});root.querySelectorAll<HTMLButtonElement>('[data-panel]').forEach(b=>b.onclick=()=>{panel=b.dataset.panel as typeof panel;void render()});root.querySelectorAll<HTMLButtonElement>('[data-back]').forEach(b=>b.onclick=()=>{panel='home';store.navigate({name:tab})});root.querySelectorAll<HTMLButtonElement>('[data-wall]').forEach(b=>b.onclick=()=>store.navigate({name:'wall',wallId:b.dataset.wall!}));root.querySelectorAll<HTMLButtonElement>('[data-new-problem]').forEach(b=>b.onclick=()=>void openProblemEditor(b.dataset.newProblem!));root.querySelectorAll<HTMLButtonElement>('[data-problem]').forEach(b=>b.onclick=()=>void openDetail(b.dataset.problem!));root.querySelectorAll<HTMLButtonElement>('[data-edit-wall]').forEach(b=>b.onclick=()=>void openWallEditor(b.dataset.editWall!));root.querySelectorAll<HTMLButtonElement>('[data-expand]').forEach(b=>b.onclick=()=>{expandedWall=expandedWall===b.dataset.expand?'':b.dataset.expand!;void render()});root.querySelectorAll<HTMLButtonElement>('[data-delete-problem]').forEach(b=>b.onclick=async()=>{await store.session.deleteProblem(b.dataset.deleteProblem!);void render()});root.querySelectorAll<HTMLButtonElement>('[data-delete-wall]').forEach(b=>b.onclick=async()=>{managementError='';try{await store.session.deleteWall(b.dataset.deleteWall!)}catch(e){const count=(await store.session.listProblems({wallId:b.dataset.deleteWall})).length;managementError=(e as Error).message.includes('WALL_IN_USE')?`无法删除：这面墙仍有 ${count} 条线路，请先删除关联线路。`:`删除失败：${(e as Error).message}`}void render()});root.querySelector<HTMLButtonElement>('[data-create-wall]')?.addEventListener('click',async()=>{const name=(root.querySelector('#wall-name') as HTMLInputElement).value.trim(),image=(root.querySelector('#wall-image') as HTMLInputElement).files?.[0],error=root.querySelector('#wall-error')!;if(!name||!image){error.textContent='请填写名称并选择图片。';return}try{const size=await imageDimensions(image),wall=await store.session.createWall({name,image,imageWidth:size.width,imageHeight:size.height});await openWallEditor(wall.id)}catch(e){error.textContent=(e as Error).message}})}
store.subscribe(()=>void render())
void api.currentUser().then(async user=>{authenticated=Boolean(user);if(user)await store.useApi(api);await render()}).catch(()=>{loginError='本地服务未启动，请先启动 FastAPI。';renderLogin()})
